# Generated by Django 5.1.2 on 2024-11-15 14:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_item_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='custom_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True, unique=True),
        ),
    ]
