# Generated by Django 5.1.2 on 2024-11-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayMent_VNpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnpay_ResponseCode', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
