# Generated by Django 5.1.2 on 2024-11-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_payment_vnpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_vnpay',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='payment_vnpay',
            name='order_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment_vnpay',
            name='order_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='payment_vnpay',
            name='vnpay_Trans',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
